name: Cloudflare Pages Deployment Status

on:
  push:
    branches: ["**"]

permissions:
  deployments: write
  contents: read

jobs:
  update-status:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Deployment
        uses: chrnorm/deployment-action@v2
        id: deployment
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          environment: ${{ github.ref_name == 'main' && 'production' || github.ref_name }}
          description: "Build & Deploy by Cloudflare Pages"

      - name: Wait for Cloudflare & Update Status
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: "evodirecte"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Deployment Status to Success
        uses: chrnorm/deployment-status@v2
        if: success()
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: "success"
          environment-url: https://${{ github.ref_name == 'main' && '' || format('{0}.', github.ref_name) }}evodirecte.qzz.io
