name: Cloudflare Pages Deployment Status

on:
  push:
    branches: ["**"]

permissions:
  deployments: write
  contents: read

jobs:
  update-status:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Deployment
        uses: chrnorm/deployment-action@v2
        id: deployment
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          environment: ${{ github.ref_name == 'main' && 'production' || github.ref_name }}
          description: "Cloudflare Pages Build"

      - name: Wait for Cloudflare Pages
        uses: un-versed/wait-for-cloudflare-pages@v1.1.0
        id: cloudflare
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          project_name: "evodirecte" 

      - name: Update Deployment Status
        uses: chrnorm/deployment-status@v2
        if: always()
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: ${{ steps.cloudflare.outputs.status == 'success' && 'success' || 'failure' }}
          environment-url: ${{ steps.cloudflare.outputs.url }}
